---
#starevent-event
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/marcelloraffaele/starevent-quarkus.git
    app.quarkus.io/build-timestamp: 2021-01-02 - 16:59:21 +0000
    app.quarkus.io/commit-id: f9e7c56ee0ba304b94271d688438356f61a11a18
  labels:
    app.kubernetes.io/name: starevent-event
    app.kubernetes.io/version: 1.0-rest
  name: starevent-event
spec:
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/name: starevent-event
    app.kubernetes.io/version: 1.0-rest
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/marcelloraffaele/starevent-quarkus.git
    app.quarkus.io/build-timestamp: 2021-01-02 - 16:59:21 +0000
    app.quarkus.io/commit-id: f9e7c56ee0ba304b94271d688438356f61a11a18
  labels:
    app.kubernetes.io/version: 1.0-rest
    app.kubernetes.io/name: starevent-event
  name: starevent-event
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0-rest
      app.kubernetes.io/name: starevent-event
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: https://github.com/marcelloraffaele/starevent-quarkus.git
        app.quarkus.io/build-timestamp: 2021-01-02 - 16:59:21 +0000
        app.quarkus.io/commit-id: f9e7c56ee0ba304b94271d688438356f61a11a18
      labels:
        app.kubernetes.io/version: 1.0-rest
        app.kubernetes.io/name: starevent-event
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: rmarcello/starevent-event:1.0-rest
        imagePullPolicy: Always
        name: starevent-event
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
---
#starevent-reservation
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/marcelloraffaele/starevent-quarkus.git
    app.quarkus.io/build-timestamp: 2021-01-02 - 12:25:12 +0000
    app.quarkus.io/commit-id: f9e7c56ee0ba304b94271d688438356f61a11a18
  labels:
    app.kubernetes.io/name: starevent-reservation
    app.kubernetes.io/version: 1.0-rest
  name: starevent-reservation
spec:
  ports:
  - name: http
    port: 8082
    targetPort: 8082
  selector:
    app.kubernetes.io/name: starevent-reservation
    app.kubernetes.io/version: 1.0-rest
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/marcelloraffaele/starevent-quarkus.git
    app.quarkus.io/build-timestamp: 2021-01-02 - 12:25:12 +0000
    app.quarkus.io/commit-id: f9e7c56ee0ba304b94271d688438356f61a11a18
  labels:
    app.kubernetes.io/name: starevent-reservation
    app.kubernetes.io/version: 1.0-rest
  name: starevent-reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: starevent-reservation
      app.kubernetes.io/version: 1.0-rest
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: https://github.com/marcelloraffaele/starevent-quarkus.git
        app.quarkus.io/build-timestamp: 2021-01-02 - 12:25:12 +0000
        app.quarkus.io/commit-id: f9e7c56ee0ba304b94271d688438356f61a11a18
      labels:
        app.kubernetes.io/name: starevent-reservation
        app.kubernetes.io/version: 1.0-rest
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: COM_RMARCELLO_STAREVENT_CLIENT_EVENTSPROXY_MP_REST_URL
          value: http://starevent-event:8081
        image: rmarcello/starevent-reservation:1.0-rest
        imagePullPolicy: Always
        name: starevent-reservation
        ports:
        - containerPort: 8082
          name: http
          protocol: TCP
---
#starevent-frontend
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/marcelloraffaele/starevent-quarkus.git
    app.quarkus.io/build-timestamp: 2021-01-02 - 16:40:28 +0000
    app.quarkus.io/commit-id: f9e7c56ee0ba304b94271d688438356f61a11a18
  labels:
    app.kubernetes.io/name: starevent-frontend
    app.kubernetes.io/version: 1.0-rest
  name: starevent-frontend
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: starevent-frontend
    app.kubernetes.io/version: 1.0-rest
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/marcelloraffaele/starevent-quarkus.git
    app.quarkus.io/build-timestamp: 2021-01-02 - 16:40:28 +0000
    app.quarkus.io/commit-id: f9e7c56ee0ba304b94271d688438356f61a11a18
  labels:
    app.kubernetes.io/version: 1.0-rest
    app.kubernetes.io/name: starevent-frontend
  name: starevent-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0-rest
      app.kubernetes.io/name: starevent-frontend
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: https://github.com/marcelloraffaele/starevent-quarkus.git
        app.quarkus.io/build-timestamp: 2021-01-02 - 16:40:28 +0000
        app.quarkus.io/commit-id: f9e7c56ee0ba304b94271d688438356f61a11a18
      labels:
        app.kubernetes.io/version: 1.0-rest
        app.kubernetes.io/name: starevent-frontend
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: COM_RMARCELLO_STAREVENT_CLIENT_EVENT_EVENTSPROXY_MP_REST_URL
          value: http://starevent-event:8081
        - name: COM_RMARCELLO_STAREVENT_CLIENT_RESERVATION_RESERVATIONPROXY_MP_REST_URL
          value: http://starevent-reservation:8082
        image: rmarcello/starevent-frontend:1.0-rest
        imagePullPolicy: Always
        name: starevent-frontend
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP